name: Build LaTeX figures
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: example-class-relations--svg
        uses: dante-ev/latex-action@latest
        with:
          root_file: E1/E1.tex
          compiler: latex
          args: -interaction=nonstopmode -shell-escape
