name: Build LaTeX figures
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: example-class-relations--svg
        uses: dante-ev/latex-action@latest
        with:
          root_file: |
            E1/E1.tex
            E2/E2.tex
            E3/E3.tex
            E4/E4.tex
            E5/E5.tex
            E6/E6.tex
            E7/E7.tex
            E8/E8.tex
            E9/E9.tex
            E10/E10.tex
            E11/E11.tex
            E12/E12.tex
            E15/E15.tex
            E16i/E16i.tex
            E17/E17.tex
            E18/E18.tex
          compiler: latex
          args: -interaction=nonstopmode -shell-escape
          
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status E*/*.pdf --porcelain)" ]; then echo "true"; else echo "false"; fi)

      - name: Update changes in GitHub repository
        if: steps.git-check.outputs.modified == 'true'
        run:  |
          git config --global user.name 'Deyan Mihaylov' 
          git config --global user.email 'd.p.mihaylov@gmail.com'
          git add E*/*.pdf
          git commit -m 'Update PDFs'
          git push
